---

Parameters:
  SecurityGroupDesc:
    Description:  Security Group Description
    Type: String

  KeyName:
    Description: Select SSH Key for Instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: "rundeck"

  amiapsouth:
    Description: AMI instance ID for ap-south-1 
    Type: AWS::EC2::Image::Id
    Default: "ami-03b5297d565ef30a6"

Resources:
  RundeckInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      DisableApiTermination: false
      ImageId: !Ref amiapsouth 
      InstanceType: t2.micro
      Monitoring: false
      SecurityGroupIds: !Ref SSHSecurityGroup
      UserData: !Base64 |
        #!/bin/bash -ex
        sudo yum install java-1.8.0
        sudo rpm -Uvh https://repo.rundeck.org/latest.rpm
        sudo yum install rundeck -y
        sudo service rundeckd start
      Tags:
        - Key: Name
          Value: RundeckDemoTesting

  # Attach EIP to newly created rundeck instance
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref RundeckInstance
    
  # Create Security Group and Configure Ingress Rules
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDesc
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 4440
          ToPort: 4440
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: rundeck-sg

Outputs: 
  InstanceID:
    Description: Instance ID
    Value: !Ref RundeckInstance

  EIP:
    Description: EIP
    Value: !Ref MyEIP

  SecGroup:
    Description: Security Group
    Value: !Ref SSHSecurityGroup